sudo: required
services:
  - docker

before_install:
  - docker build -t machinedatainsights/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true machinedatainsights/react-test npm test

after_success:
  - docker build -t machinedatainsights/multi-client ./client
  - docker build -t machinedatainsights/multi-nginx ./nginx
  - docker build -t machinedatainsights/multi-server ./server
  - docker build -t machinedatainsights/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take these images and push them to Docker Hub
  - docker push machinedatainsights/multi-client 
  - docker push machinedatainsights/multi-nginx
  - docker push machinedatainsights/multi-server
  - docker push machinedatainsights/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker2'
  env: 'Multidocker2-env'
  bucket_name: 'elasticbeanstalk-us-east-1-621035315092'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

